[tool.black]
line-length = 79
[tool.isort]
multi_line_output=3
include_trailing_comma=true
force_grid_wrap=0
combine_as_imports=true
use_parentheses=true
line_length=79
sections=["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
